// Shell completion script generators + installer.
//
// `club completion <shell>` prints a script that, when sourced (bash/zsh) or
// dropped into fish's completions dir, wires TAB-completion for `club`. Every
// script delegates the actual candidate computation to `club __complete`
// (see ./complete.ts), so the static glue never goes stale when commands change
// -- only the dispatcher, which introspects the live commander tree, is truth.
//
// Output protocol: `club __complete` prints one candidate per line as
// `value[\tdescription]`. bash strips the description (it can't render them);
// zsh's `_describe` and fish both natively render `value\tdescription`.

import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export type Shell = "bash" | "zsh" | "fish";
export const SHELLS: readonly Shell[] = ["bash", "zsh", "fish"] as const;

const MARKER = "# >>> club completion >>>";

/** Bash completion script. Source it (or `club completion bash --install`). */
export function bashScript(): string {
  return `# club bash completion - delegates to \`club __complete\`.
# Generated by \`club completion bash\`. Source this file, or run
# \`club completion bash --install\` to wire it into ~/.bashrc automatically.
_club_completion() {
  local cur out cand
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  # Hand the full token list (sans the program name) to the dispatcher. The
  # final element is the word being completed and may be empty, so quote it.
  out=$(club __complete "\${COMP_WORDS[@]:1}" 2>/dev/null) || return
  [[ -z "$out" ]] && return
  local IFS=$'\\n'
  for cand in $out; do
    cand="\${cand%%$'\\t'*}"   # drop description; bash renders values only
    [[ "$cand" == "$cur"* ]] && COMPREPLY+=("$cand")
  done
}
# -o default: fall back to filename completion when the dispatcher offers
# nothing (e.g. \`club send --image <TAB>\`, or \`club agent -- <TAB>\`).
complete -o default -F _club_completion club
`;
}

/** Zsh completion script. Source it (or `club completion zsh --install`). */
export function zshScript(): string {
  return `# club zsh completion - delegates to \`club __complete\`.
# Generated by \`club completion zsh\`. Source this file, or run
# \`club completion zsh --install\` to wire it into ~/.zshrc automatically.
_club() {
  local -a lines comps
  local line value desc
  # $words[1] is the command name; pass the rest (incl. the word being typed).
  lines=("\${(@f)\$(club __complete "\${words[@]:1}" 2>/dev/null)}")
  for line in $lines; do
    if [[ $line == *$'\\t'* ]]; then
      value="\${line%%$'\\t'*}"
      desc="\${line#*$'\\t'}"
      comps+=("\${value}:\${desc}")
    else
      comps+=("$line")
    fi
  done
  if (( \${#comps} == 0 )); then
    _files        # nothing from the dispatcher (e.g. --image <path>) -> files
    return
  fi
  _describe 'club' comps
}
compdef _club club
`;
}

/** Fish completion script. Place in ~/.config/fish/completions/club.fish. */
export function fishScript(): string {
  return `# club fish completion - delegates to \`club __complete\`.
# Generated by \`club completion fish\`. fish auto-loads this from
# ~/.config/fish/completions/club.fish; run \`club completion fish --install\`
# to place it there automatically.

# Subcommands, flags, and dynamic values (channels/members) from the dispatcher.
complete -c club -f -a '(club __complete (commandline -opc)[2..] 2>/dev/null)'

# File completion for path-valued options (the dispatcher offers none for these).
complete -c club -l image -r -F
complete -c club -l video -r -F
complete -c club -l file  -r -F
complete -c club -s c -l config -r -F
`;
}

/** Return the completion script for the given shell. */
export function getScript(shell: Shell): string {
  if (shell === "bash") return bashScript();
  if (shell === "zsh") return zshScript();
  return fishScript();
}

/** Best-effort detect the user's shell from $SHELL. */
export function detectShell(): Shell | null {
  const shell = process.env.SHELL ?? "";
  if (shell.endsWith("zsh")) return "zsh";
  if (shell.endsWith("fish")) return "fish";
  if (shell.endsWith("bash")) return "bash";
  return null;
}

export interface InstallResult {
  /** Path the completion script was written to. */
  scriptPath: string;
  /** Rc file that was (or already was) sourcing the script (bash/zsh only). */
  rcPath?: string;
  /** True if this run wrote/changed something; false if already installed. */
  installed: boolean;
}

/**
 * Install the completion script for `shell`: writes the script to
 * `~/.club/completion.<shell>` and adds a `source` line to the rc file
 * (bash/zsh), or drops it into fish's completions dir (auto-loaded). Idempotent
 * via the `>>> club completion >>>` marker comment.
 */
export function installCompletion(shell: Shell): InstallResult {
  const clubDir = join(homedir(), ".club");
  mkdirSync(clubDir, { recursive: true });
  const script = getScript(shell);

  if (shell === "fish") {
    const fishDir = join(homedir(), ".config", "fish", "completions");
    mkdirSync(fishDir, { recursive: true });
    const fishPath = join(fishDir, "club.fish");
    const already = existsSync(fishPath) && readFileSync(fishPath, "utf8") === script;
    if (!already) writeFileSync(fishPath, script, { mode: 0o644 });
    return { scriptPath: fishPath, installed: !already };
  }

  const scriptPath = join(clubDir, `completion.${shell}`);
  writeFileSync(scriptPath, script, { mode: 0o644 });

  const rcName = shell === "zsh" ? ".zshrc" : ".bashrc";
  const rcPath = join(homedir(), rcName);
  const sourceLine = `[ -f "${scriptPath}" ] && source "${scriptPath}"  ${MARKER}`;
  const existing = existsSync(rcPath) ? readFileSync(rcPath, "utf8") : "";
  if (existing.includes(MARKER)) {
    return { scriptPath, rcPath, installed: false };
  }
  const lead = existing && !existing.endsWith("\n") ? "\n" : "";
  appendFileSync(rcPath, `${lead}${sourceLine}\n`);
  return { scriptPath, rcPath, installed: true };
}
